[build-system]   # ---------------------------------------------------------------------

requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.mypy]  # -------------------------------------------------------------------------

check_untyped_defs = true
# See <https://github.com/python/mypy/issues/10250#issuecomment-899187636>
exclude = """(?x)(
  (^|/)build/
)"""
ignore_missing_imports = true
strict_optional = true
warn_redundant_casts = true
warn_unused_configs = true
