[tox]
envlist = py{311,312,313,314}{,-beartype}, pypy{311}
isolated_build = true

[testenv]
deps =
    pytest>=8
    !pypy{311}: pytest-beartype
commands =
    beartype-!pypy{311}: pytest --beartype-packages dyce {posargs}
    !beartype: pytest {posargs}
