# ======================================================================================
# Copyright and other protections apply. Please see the accompanying LICENSE file for
# rights and restrictions governing use of this software. All rights not expressly
# waived or licensed are reserved. If that file is missing or appears to be modified
# from its original, then please contact the author before viewing or using this
# software in any capacity.
# ======================================================================================

[tox]  # -------------------------------------------------------------------------------

envlist = check, py{310,311,312}{,-beartype,-lint}, py{313,313t,314,314t}{,-beartype}, py{313,314}-lint, pypy{310,311}
skipsdist = true
skip_missing_interpreters = true

[gh-actions]  # ------------------------------------------------------------------------

python =
  3.10: py310{,-beartype,-lint}
  3.11: py311{,-beartype,-lint}
  3.12: py312{,-beartype,-lint}
  3.13: py313{,-beartype,-lint}
  3.13t: py313t{,-beartype}
  3.14: py314{,-beartype,-lint}
  3.14t: py314t{,-beartype}
  pypy-3.10: pypy310
  pypy-3.11: pypy311
fail_on_no_env = True

[testenv]  # ---------------------------------------------------------------------------

commands =
  pytest --cov=dyce --durations 5 --numprocesses {env:NUMBER_OF_PROCESSORS:auto} {posargs}
deps =
  --editable .
  !pypy310-!pypy311: numpy  # see <https://github.com/beartype/beartype/issues/324>
  pytest
  # Because ${HOME} is not passed, ~/.gitconfig is not read. To overcome this, port any
  # desired user-specific exclusion configuration to .git/config. E.G.:
  #
  #   [core]
  #   excludesfile = /home/username/.gitignore
  #
  # Alternatively, add entries directly to .git/info/exclude. See also mkdocs-exclude
  # below.
  pytest-gitignore
  debug: debugpy
  debug: ipython
  !debug: pytest-cov
  !debug: pytest-xdist
  sympy
passenv =
  PYTHONBREAKPOINT
setenv =
  beartype: NUMERARY_BEARTYPE = yes
  !beartype: NUMERARY_BEARTYPE = no
  PYTHONWARNINGS = {env:PYTHONWARNINGS:ignore}

[testenv:assets]  # --------------------------------------------------------------------

base_python = 3.13  # should match python-version in GitHub Actions config
commands =
  make -C docs/assets -j {env:NUMBER_OF_PROCESSORS:6}
  make -C docs/assets perf
deps =
  --editable .
  anydyce~=0.4.6  # for docs/assets/plot….py
  graphviz
  jinja2  # for pandas DataFrame styles
  matplotlib
  pandas
  sympy
  pygraphviz
  pylint  # contains pyreverse
allowlist_externals =
  make

[testenv:check]  # ---------------------------------------------------------------------

base_python = 3.13  # should match python-version in GitHub Actions config
commands =
  git clean -X -d --force -- docs site
  cp LICENSE docs/license.md
  cp README.md docs/index.md
  jupyter lite build --output-dir docs/jupyter
  mkdocs build --strict
  uv build --wheel --out-dir dist .
  twine check dist/*
deps =
  --editable .
  jupyterlab_server
  jupyterlite~=0.7
  jupyterlite-pyodide-kernel
  pkginfo
  mike
  # See <https://github.com/mkdocs/mkdocs/issues/2448>
  # See <https://github.com/mkdocstrings/mkdocstrings/issues/295>
  mkdocs!=1.2
  mkdocs-exclude
  mkdocs-macros-plugin
  mkdocs-material
  mkdocstrings-python
  ruff
  sympy
  twine
  versioningit
allowlist_externals =
  cp
  git
  rm

[testenv:jupyter]  # -------------------------------------------------------------------

commands =
  jupyter-lab {posargs}
deps =
  --editable .
  jupyterlab

[testenv:py3{10,11,12}-debug, py3{13,14}{,t}-debug, pypy3{10,11}-debug]  # -------------

commands =
  pytest --capture=no --pdb --pdbcls=IPython.terminal.debugger:TerminalPdb {posargs}

[testenv:py3{10,11,12,13,14}-lint]  # --------------------------------------------------

commands =
  pre-commit run --all-files --show-diff-on-failure
  mypy --config-file={toxinidir}/pyproject.toml .
  {toxinidir}/helpers/mypy-doctests.py -a=--config-file={toxinidir}/pyproject.toml .
deps =
  --editable .
  mypy
  pre-commit
  # For type checking
  anydyce~=0.4.6
  graphviz
  jinja2
  matplotlib
  pandas-stubs
  pytest
  pygraphviz
  sympy
setenv =
  # Disable pip's cachecontrol to avoid read-timeout hangs in sandboxes
  PIP_NO_CACHE_DIR = 1
allowlist_externals =
  {toxinidir}/helpers/mypy-doctests.py
