[tox]
envlist = py{311,312,313,314}{,-beartype}, pypy{311}
isolated_build = true

[testenv]
commands =
    beartype-!pypy{311}: pytest --beartype-packages dyce {posargs}
    !beartype: pytest {posargs}
dependency_groups =
    !pypy311: test
    pypy311: test-pypy
package = editable
