name: docs

on:
  push:
    tags: ["v*"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0  # required for setuptools-scm
      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          cache-python: true
      - run: uv sync --no-dev --group docs
      - run: git config user.name "github-actions[bot]"
      - run: git config user.email "github-actions[bot]@users.noreply.github.com"
      - run: |
          FULL_VERSION=$(python -c "import importlib.metadata; print(importlib.metadata.version('dyce'))")
          MINOR_VERSION=$(python -c "
          v = '$FULL_VERSION'.split('.')
          print(f'{v[0]}.{v[1]}')
          ")
          uv run mike deploy --push --update-aliases "$MINOR_VERSION" latest
