name: docs

on:
  push:
    tags: ["v*"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0   # required for setuptools-scm
      - uses: astral-sh/setup-uv@v8.1.0
      - run: uv sync --no-dev --group docs
      - run: git config user.name "github-actions[bot]"
      - run: git config user.email "github-actions[bot]@users.noreply.github.com"
      - run: |
          FULL_VERSION=$(python -c "import importlib.metadata; print(importlib.metadata.version('dyce'))")
          MINOR_VERSION=$(python -c "
          v = '$FULL_VERSION'.split('.')
          print(f'{v[0]}.{v[1]}')
          ")
          uv run mike deploy --push --update-aliases "$MINOR_VERSION" latest
