name: tests

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { python: "3.11",     tox-env: "py311" }
          - { python: "3.11",     tox-env: "py311-beartype" }
          - { python: "3.12",     tox-env: "py312" }
          - { python: "3.12",     tox-env: "py312-beartype" }
          - { python: "3.13",     tox-env: "py313" }
          - { python: "3.13",     tox-env: "py313-beartype" }
          - { python: "3.14",     tox-env: "py314" }
          - { python: "3.14",     tox-env: "py314-beartype" }
          - { python: "pypy3.11", tox-env: "pypy311" }
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0   # required for setuptools-scm
      - uses: astral-sh/setup-uv@v8.1.0
        with:
          python-version: ${{ matrix.python }}
      - run: uv sync --no-dev --group tox
      - run: uv run tox -e ${{ matrix.tox-env }}

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0   # required for setuptools-scm
      - uses: astral-sh/setup-uv@v8.1.0
        with:
          python-version: "3.13"
      - run: uv sync --no-dev --group test
      - run: uv run pytest --cov --cov-report=xml
      - run: uv run coverage report --format=markdown >> $GITHUB_STEP_SUMMARY
      - uses: codecov/codecov-action@v5.5.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0   # required for setuptools-scm
      - uses: astral-sh/setup-uv@v8.1.0
        with:
          python-version: "3.13"
      - run: uv sync --no-dev --group lint
      - run: uv run ruff check .
      - run: uv run ruff format --check .
      - run: uv run mypy
      - run: uv run pyright
      - run: uv run pyrefly check --warn unused-ignore
      - run: uv run ty check
      - run: uv run ./helpers/check-doctests.py check
      - run: uv run ./helpers/check-doctests.py format
