name: tests

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { python: "3.11",     tox-env: "py311" }
          - { python: "3.11",     tox-env: "py311-beartype" }
          - { python: "3.12",     tox-env: "py312" }
          - { python: "3.12",     tox-env: "py312-beartype" }
          - { python: "3.13",     tox-env: "py313" }
          - { python: "3.13",     tox-env: "py313-beartype" }
          - { python: "3.14",     tox-env: "py314" }
          - { python: "3.14",     tox-env: "py314-beartype" }
          - { python: "pypy3.11", tox-env: "pypy311" }
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0  # required for setuptools-scm
      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          python-version: ${{ matrix.python }}
          cache-python: true
      - run: uv sync --no-dev --group tox
      - run: uv run tox -e ${{ matrix.tox-env }}

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0  # required for setuptools-scm
      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          cache-python: true
      - run: uv sync --no-dev --group test
      - run: uv run pytest --cov --cov-report=xml
      - run: uv run coverage report --format=markdown >> $GITHUB_STEP_SUMMARY
      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0  # required for setuptools-scm
      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          cache-python: true
      - run: uv sync --no-dev --group lint
      - run: uv run pre-commit run --all-files --hook-stage pre-push
      - run: git diff --quiet HEAD --  # fails if any tracked files have changed

  docs-idempotent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0  # required for setuptools-scm
      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          cache-python: true
      - run: uv sync --no-dev --group docs
      - run: uv run mkdocs build
        # Files can be excluded by adding, e.g.
        # ':(exclude)docs/assets/perf_*.txt' to the pathspecs
      - run: git diff --exit-code -- docs/notebooks docs/assets
